# docker run --name nestjs-api -p 5432:5432 -e POSTGRES_ROOT_PASSWORD=postgres -d postgres:latest

version: '3'

networks:
  nestjs_api:
    driver: bridge

services:
  db:
    image: postgres
    networks:
      - nestjs_api
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "nestjs_api"
    ports:
      - "5432:5432"

      